### PR TITLE
added option to hide password as it is written, for Sublime Text 3

### PR DESCRIPTION
**Pull request by circulosmeos**
It runs on Sublime Text 3. I haven't tested this on ST2.

### CODE REVIEW

**Comment by Kristinita** [comment]
@mediaupstream , please, review this pull request.

Thanks.

**Comment by mediaupstream** [comment]
Thanks @circulosmeos for the PR. I have implemented this feature now, however I couldn't use your code because it had a few bugs:
- Password couldn't be empty
- Password couldn't contain the `hide_char` character
- Didn't work in ST2
I'm glad you sent the PR though, it was helpful to see how this could be implemented

**Comment by circulosmeos** [comment]
Glad the code was useful.

I don't allow empty passwords, 'cause I consider them another way of aborting the action.
Please, consider also the treatment of backspace char (at least for me it doesn't work).

Greetings!

**Comment by mediaupstream** [comment]
@circulosmeos Yikes! I can't believe I didn't notice that bug. Anyway it's fixed now and I just pushed the changes. There is a chance this will affect someones ability to decrypt a document, if they had encrypted a document and used backspace the password would have an asterisk where the backspace was!!
so for example you could end up with a password that looks like `passwp*ord` if you mistyped the `o` as a `p` and then hit backspace and continued... 
Hopefully if this caused problems for someone they could easily crack the erroneous password by substituting lot's of asterisks in their normal password in places they might have backspace'd .....

**Comment by mediaupstream** [comment]
I prefer to allow empty string as it still does encrypt the data, it's a terrible password, but so is "password" or "letmein" or a single character password like "P". I don't want to enforce any password strength rules in this project

**Pull request closed without merging**
